version: '3.6'
services:

  app-webapp:
    container_name: 'app-webapp'
    image: 'app-webapp'
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - NODE_ENV='development
    ports:
      - '3000:3000'
    command: yarn hot
