version: '3.6'
services:

  app-webapp:
    container_name: 'app-webapp'
    image: 'app-webapp'
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
    environment:
      - NODE_ENV='development
    command: yarn hot

  app-nginx:
    container_name: 'app-nginx'
    image: 'app-nginx'
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    networks:
      - app-network

networks:
  app-network: